version: '3'

tasks:
  install:
    aliases: [i]
    desc: Install dependencies (excluding pip)
    cmds:
      - rm -rf botw
      - python src/setup.py {{.CLI_ARGS}}

  build:
    aliases: [b]
    desc: Build the research data
    cmds:
      - python src/main.py

  clean:
    desc: Delete the build output
    cmds:
      - rm -rf output
